### ISSUE TITLE
Declaration of SaintSystems\Nova\LinkableMetrics\LinkableTrend::result($value) should be compatible with Laravel\Nova\Metrics\Trend::result($value = NULL)

### ISSUE THREAD

**Issue by markrassamni** [saintsystems/nova-linkable-metrics#1]
<img width="841" alt="Screen Shot 2019-04-12 at 10 20 08 PM" src="https://user-images.githubusercontent.com/17393438/56075064-4877a900-5d71-11e9-9f31-2623f1803e2c.png">

Getting this error when trying to use the linkable trait in a trend metric

**Comment by anderly** [comment]
@markrassamni should be fixed now in 0.0.5. Please try updating and let me know if you still see any issues.
