### ISSUE TITLE
Adding LinkableValue trait disrupts time formatting

### ISSUE THREAD

**Issue by CitizenBeta** [saintsystems/nova-linkable-metrics#12]
I have a metric card that uses ->format('output: "time"'). Without any other changes, simply adding "use LinkableValue" at the top changes the time output 00:00:00 to "0th". Is there something I should be doing differently?

**Comment by CitizenBeta** [comment]
I'm willing to donate for a fix if that's an option. Not sure how/if this is maintained.

**Comment by anderly** [comment]
@CitizenBeta looking into this today. Stay tuned...

**Comment by CitizenBeta** [comment]
Any update on this? Seems like extending the card would be the way to go on this instead of replacing the card with a totally custom one. I just posted another issue that sounds like the vue card is just out of date.

**Comment by anderly** [comment]
We just published an update (0.1.0) in commit 5d8a765 that brings 3.x compatibility. Please update and let me know if the problem persists.
