### ISSUE TITLE
Is this still maintained?

### ISSUE THREAD

**Issue by CitizenBeta** [saintsystems/nova-linkable-metrics#13]
Sometimes nova packages stop getting maintained because there's a native solution. Is that the case here? Is there any other way to solve for linkable metrics?

**Comment by anderly** [comment]
@CitizenBeta hi there! This package is still maintained, but we haven't yet been able to come back and address some of the open issues. There is not another way to solve linkable metrics that I'm aware of. Let me know if you've run into any issues and what version of Nova you're running. We're using this package on current projects running Nova 2.x.

**Comment by CitizenBeta** [comment]
Thanks for the update, right now it's just the formatting issue from the other that I posted. I did try poking into it to see if I could help solve the issue, but it looks like maybe the base problem is that the card vue code itself is a copy of an older card from what I can tell. Should/could we just be extending the main nova card?

**Comment by anderly** [comment]
We just published an update (0.1.0) in commit 5d8a765 that brings 3.x compatibility. Please update and let me know if the problem persists.
