### ISSUE TITLE
allowZeroResult() doesn't work with LinkableValue trait.

### ISSUE THREAD

**Issue by CitizenBeta** [saintsystems/nova-linkable-metrics#16]
For instance:

` return $this->result($ticketCount)->allowZeroResult()->route('index', ['resourceName' => 'tickets'], ['tickets_filter' => $filters]);`

Still loads the "No current data" text, whereas on a regular card adding allowZeroResult() would hide the no current data text.

**Comment by anderly** [comment]
We just published an update (0.1.0) in commit 5d8a765 that brings 3.x compatibility. Please update and let me know if the problem persists.
