### ISSUE TITLE
How do I link to a specific resource?

### ISSUE THREAD

**Issue by keironwaites** [saintsystems/nova-linkable-metrics#24]
I am building a queuing system - when the user clicks on the linkable value I want to take them to a specific resource.

I am calling:

->route('index', ['resourceName' => 'members'])

Can I add an additional argument that will allow me to generate a URL like the following?

/resources/members/3838383

Thank you.

**Comment by anderly** [comment]
@keironwaites, yes, you should be able to just append the ID to the resourceName and do something like:

`->route('index', ['resourceName' => 'members/' . $resourceId])`

**Comment by anderly** [comment]
@keironwaites correction, make sure you change the route name to `detail` and pass the `$resourceId` as a separate item in the params array like so:

`->route('detail', ['resourceName' => 'members', 'resourceId' => $resourceId])`
