### ISSUE TITLE
Metrics no longer appear when using this package, no error messages.

### ISSUE THREAD

**Issue by nickbluestone98** [saintsystems/nova-linkable-metrics#36]
I have installed the addon and when I use it within any of my metrics they no longer render on the dashboard. I have no errors at all.  

code below:

```
use SaintSystems\Nova\LinkableMetrics\LinkableValue;

class PendingOrders extends Value
{
    use LinkableValue;
   
    //my class code
}
```

In my Nova Service Provider:

```
protected function cards()
{
        return [
              (new PendingOrders)->route('index', ['resourceName' => 'orders']),
        ]
}
```

When I refresh there is just a blank gap where the metric should render.

**Comment by anderly** [comment]
Please checkout the just released version 4.0.0.
