### ISSUE TITLE
resourceName with slash

### ISSUE THREAD

**Issue by Patrick235U** [saintsystems/nova-linkable-metrics#4]
![Przechwytywanie](https://user-images.githubusercontent.com/6717593/57200206-462bf780-6f89-11e9-8312-20ec05517d8d.PNG)

My URL looks like this:
`https://xxx/nova/resources/bids%2Flens%2Fwon-pre-bids`

Slashes have been replaced with %2

**Comment by anderly** [comment]
@Patrick235U, since you're wanting to link to a `lens` route, here is the format you need since these routes are generated on the client/vue side using router-link:

```
(new WonPreBids)->width('1/3')->route('lens', ['resourceName' => 'bids', 'lens' => 'won-pre-bids']),
```
