### ISSUE TITLE
Metric card is not respecting calls to allowZeroResult()

### ISSUE THREAD

**Issue by andrefedalto** [saintsystems/nova-linkable-metrics#46]
When you use `return $this->result(0)->allowZeroResult()` in your `calculate` method, it should not display the phrase `No Current Data` in your card. 

Nova default metric card is working as expected, but not the one from this package.

Digging a bit into the source code I found out that `ValueMetric.vue` from this package has this logic:
```
                <span v-else>
                    <span v-if="previous == '0' && value != '0'">
                        {{ __('No Prior Data') }}
                    </span>

                    <span v-if="value == '0' && previous != '0'">
                        {{ __('No Current Data') }}
                    </span>

                    <span v-if="value == '0' && previous == '0'">
                        {{ __('No Data') }}
                    </span>
                </span>```

But the code from Nova reads:
```
        <span v-else>
          <span v-if="previous == '0' && value != '0'">
            {{ __('No Prior Data') }}
          </span>

          <span v-if="value == '0' && previous != '0' && !zeroResult">
            {{ __('No Current Data') }}
          </span>

          <span v-if="value == '0' && previous == '0' && !zeroResult">
            {{ __('No Data') }}
          </span>
        </span>```
        
It seems this package is missing the `&& !zeroResult` bit, which is what is causing the unexpected behavior.

**Comment by anderly** [comment]
Please checkout the just released version 4.0.0.
