### ISSUE TITLE
Nova 4 support?

### ISSUE THREAD

**Issue by vesper8** [saintsystems/nova-linkable-metrics#49]
Anyone got a fork that's working on Nova 4? The front-end components need to be re-built with Vue 3 and I've been struggling to get a working solution

**Comment by anderly** [comment]
I know it's late, but just released version 4.0.0 to bring Nova 4 support.

**Comment by vesper8** [comment]
@anderly that's awesome!!! This was one of those plugins I was missing the most!! Thanks a lot!
