### ISSUE TITLE
Can we link to a resource with a filter?

### ISSUE THREAD

**Issue by CitizenBeta** [saintsystems/nova-linkable-metrics#5]
Does it have to be a lens or can we link with a filter? Would be great to be able to do that as well.

**Comment by CitizenBeta** [comment]
Figured it out. Might be cool to add to the documentation:

```
$filters = base64_encode(json_encode([
    [
        'class' => UserStatus::class,
        'value' => 'active',
    ],
]));

return $this->result($result)->route('index', ['resourceName' => 'users'], ['users_filter' => $filters]);
```

**Comment by anderly** [comment]
I’ll add to the readme.

**Comment by anderly** [comment]
Added example to readme. Just curious, are you using it in your NovaServiceProvider when the card is registered or within the card itself? Would you mind sharing your full example?

Thanks!
