### ISSUE TITLE
feature: trend metric with date

### ISSUE THREAD

**Issue by otrsw** [saintsystems/nova-linkable-metrics#6]
Hi there

Thank you for a really nice component.  I would like to suggest a feature to add (or perhaps you can suggest a way to achieve this with existing component)

When clicking on a trend metric, it would be great to receive the date that was clicked so we can link to relevant detail and not just one location for the entire trend.

**Comment by oseintow** [comment]
@otrsw been trying to get the trend to work but to no avail. I don' know what am missing. Can you give me an example.

**Comment by anderly** [comment]
This should be fixed in [0.0.6](https://github.com/saintsystems/nova-linkable-metrics/releases/tag/0.0.6)

**Comment by anderly** [comment]
This isn't currently supported to have different links based on where the user clicked on the trend line because the trend chart is generated by the Chartist plugin. Closing for now.
