### ISSUE TITLE
LinkablePartition function result unable to handle PartitionResult

### ISSUE THREAD

**Issue by drsdre** [saintsystems/nova-linkable-metrics#7]
The result() function in LinkablePartition input type (array) is incompatible with the output of the query (PartitionResult). Found on Laravel Nova 2.0.5.

For example when the following is used in the calculate() function of a Partition metric:

	return $this->result(
		$this->count( $request, $data_query, 'status' )
	)->route( 'index', $route_params, $route_query );

This fails with error:

> Argument 1 passed to App\Nova\Metrics\GamesPerStatus::result() must be of the type array, object given

Unfortunately this cannot be fixed by changing input type from array to in LinkablePartition.php:

	public function result(PartitionResult $value)

as this results in:

> Declaration of SaintSystems\Nova\LinkableMetrics\LinkablePartition::result(Laravel\Nova\Metrics\PartitionResult $value) should be compatible with Laravel\Nova\Metrics\Partition::result(array $value)

**Comment by anderly** [comment]
We just published an update (0.1.0) in commit 5d8a765 that brings 3.x compatibility. Please update and let me know if the problem persists.
