### ISSUE TITLE
Range select box is not populating

### ISSUE THREAD

**Issue by ChrisReid** [saintsystems/nova-linkable-metrics#9]
![Screenshot 2019-06-24 at 08 13 16](https://user-images.githubusercontent.com/2385373/59998725-1da2ae80-9658-11e9-8ce7-811efef3a295.png)

When you select a different date range, the box re-renders with the updated figure correctly, but the select box doesn't populate with the value. It looks like an issue with the components. Should be easy to fix but I can't work out how to recompile the assets.

**Comment by ChrisReid** [comment]
Reference pull request #10

**Comment by CitizenBeta** [comment]
I'm still running into this issue.
